pipeline{
    agent{
        docker{
            image "node:slim"
            args "-p 3004:3000"
        }
    }

    stages{
        stage('checkout'){
            // git url: "https://github.com/biplabtharu/jenkins/blob/main/simple-node-js-react-npm-app" branch: "main"
            steps{
                checkout scm
            }
        }

        stage('build'){
            steps{
                dir('simple-node-js-react-npm-app'){
                    sh "npm install"
                }
            }
        }

        // stage('test'){
        //     steps{
        //         dir('simple-node-js-react-npm-app'){
        //             sh "chmod "
        //             sh "./jenkins/scripts/test.sh"
        //         }
        //     }
        // }
    }
}