pipeline{
    agent{
        docker{
            image "node:18"
            args "-p 3004:3000"
            args "-u node"
        }
    }

    environment{
        HOME = '/home/node'
    }

    stages{
        stage('checkout'){
            // git url: "https://github.com/biplabtharu/jenkins/blob/main/simple-node-js-react-npm-app" branch: "main"
            steps{
                checkout scm
            }
        }

        stage('Debug Environment') {
            steps {
                sh '''
                    echo "User: $(whoami)"
                    echo "HOME: $HOME"
                    echo "npm cache location: $(npm config get cache)"
                '''
            }
        }

        stage('build'){
            steps{
                sh "npm install"
            }
        }

        // stage('test'){
        //     steps{
        //             sh "chmod "
        //             sh "./jenkins/scripts/test.sh"
        //     }
        // }
    }
}